export function downloadCsvFile(filename: string, rows: Record<string, unknown>[]) {
  if (!rows.length) return;
  const headers = Object.keys(rows[0]);
  const encode = (value: unknown) => `"${String(value ?? "").split('"').join('""')}"`;
  const csv = `${headers.join(",")}\n${rows.map((row) => headers.map((h) => encode(row[h])).join(",")).join("\n")}`;
  const blob = new Blob([csv], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export function exportDatasetToExcel(datasetName: string, rows: Record<string, unknown>[]) {
  downloadCsvFile(`${datasetName}.csv`, rows);
}

export function exportSectionToPdf(sectionId?: string) {
  if (sectionId) {
    const target = document.getElementById(sectionId);
    if (target) target.setAttribute("data-print-target", "true");
  }
  window.print();
}

export function exportPortfolioPdf() {
  exportSectionToPdf("portfolio-root");
}

export function exportCustomerPdf(customerSlug: string) {
  exportSectionToPdf(`customer-${customerSlug}`);
}

/* ── Structured Export Helpers ── */

export interface ExportableSpec {
  title: string;
  rm_numbers: string[];
  customer: string;
  author: string;
  status: string;
  request_overview: string;
  goals: string;
  scope: string;
  specification: string;
  open_questions: string;
  created_at: string;
}

export function exportSpecToCsv(spec: ExportableSpec) {
  downloadCsvFile(`spec-${spec.title.replace(/\s+/g, "-").toLowerCase()}.csv`, [{
    Title: spec.title,
    "RM Numbers": spec.rm_numbers.join(", "),
    Customer: spec.customer,
    Author: spec.author,
    Status: spec.status,
    "Request Overview": spec.request_overview,
    Goals: spec.goals,
    Scope: spec.scope,
    Specification: spec.specification,
    "Open Questions": spec.open_questions,
    Created: spec.created_at,
  }]);
}

export function exportSpecToText(spec: ExportableSpec): string {
  const sep = "═".repeat(60);
  return [
    sep,
    `SPECIFICATION: ${spec.title}`,
    sep,
    `Customer: ${spec.customer}`,
    `Author: ${spec.author}`,
    `Status: ${spec.status}`,
    `RM Numbers: ${spec.rm_numbers.join(", ") || "—"}`,
    `Date: ${new Date(spec.created_at).toLocaleDateString()}`,
    "",
    "─── REQUEST OVERVIEW ───",
    spec.request_overview || "N/A",
    "",
    "─── GOALS ───",
    spec.goals || "N/A",
    "",
    "─── SCOPE OF CHANGES ───",
    spec.scope || "N/A",
    "",
    "─── SPECIFICATION ───",
    spec.specification || "N/A",
    "",
    "─── OPEN QUESTIONS / CONSIDERATIONS ───",
    spec.open_questions || "N/A",
    "",
    sep,
    `Generated by NÈKO · Mike Nichols · ${new Date().toLocaleDateString()}`,
  ].join("\n");
}

export function downloadTextFile(filename: string, content: string) {
  const blob = new Blob([content], { type: "text/plain;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export function exportCustomerTrackerCsv(
  customerName: string,
  tickets: { rm_number: string; title: string | null; status: string; owner: string | null; last_update: string | null; due_date: string | null; next_steps: string | null; open_questions: string | null }[]
) {
  downloadCsvFile(`${customerName.replace(/\s+/g, "-").toLowerCase()}-tracker.csv`, tickets.map((t) => ({
    "RM Number": t.rm_number,
    Title: t.title || "",
    Status: t.status,
    Owner: t.owner || "",
    "Last Update": t.last_update || "",
    "Due Date": t.due_date || "",
    "Next Steps": t.next_steps || "",
    "Open Questions": t.open_questions || "",
  })));
}

export function exportMeetingMinutesTxt(meeting: {
  title: string; date: string; attendees: string[]; summary: string | null;
  decisions: string[]; next_steps: string[]; open_questions: string[];
}) {
  const content = [
    `MEETING MINUTES: ${meeting.title}`,
    `Date: ${meeting.date}`,
    `Attendees: ${meeting.attendees.join(", ")}`,
    "",
    "── SUMMARY ──",
    meeting.summary || "N/A",
    "",
    "── DECISIONS ──",
    ...meeting.decisions.map((d) => `• ${d}`),
    "",
    "── NEXT STEPS ──",
    ...meeting.next_steps.map((s) => `→ ${s}`),
    "",
    "── OPEN QUESTIONS ──",
    ...meeting.open_questions.map((q) => `? ${q}`),
    "",
    `Generated by NÈKO · ${new Date().toLocaleDateString()}`,
  ].join("\n");
  downloadTextFile(`meeting-${meeting.date}-${meeting.title.replace(/\s+/g, "-").toLowerCase()}.txt`, content);
}

export function exportWeeklySummaryTxt(summary: {
  title: string; date: string; sections: { heading: string; items: string[] }[];
}) {
  const content = [
    `${summary.title}`,
    `Date: ${summary.date}`,
    "═".repeat(50),
    ...summary.sections.flatMap((s) => ["", `── ${s.heading.toUpperCase()} ──`, ...s.items.map((i) => `• ${i}`)]),
    "",
    `Generated by NÈKO · Mike Nichols`,
  ].join("\n");
  downloadTextFile(`${summary.title.replace(/\s+/g, "-").toLowerCase()}-${summary.date}.txt`, content);
}
